package lotsoffood.common;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

public class FoodValues {
    public static final int BRIEF_DURATION = 600;;
    public static final FoodProperties SPICY_CHOCOLATE = new FoodProperties.Builder().nutrition(10).saturationModifier(1.0f).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED), 10).alwaysEdible().build();
    public static final FoodProperties CHOCOLATE = new FoodProperties.Builder().nutrition(5).saturationModifier(1.5f).build();
    public static final FoodProperties HALFCOCONUT = new FoodProperties.Builder().nutrition(2).saturationModifier(0.1f).build();
    public static final FoodProperties WHITE_CHOCOLATE = new FoodProperties.Builder().nutrition(5).saturationModifier(1.8f).build();
    public static final FoodProperties APPLE_JUICE= new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties TOMATE = new FoodProperties.Builder().nutrition(3).saturationModifier(0.5f).build();
    public static final FoodProperties CHILI = new FoodProperties.Builder().nutrition(1).saturationModifier(1.0f)
            .effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, BRIEF_DURATION), 1.0f)
            .build();
    public static final FoodProperties ZOMBIEPURE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.0f).build();
    public static final FoodProperties BANANE = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties STRAWBERRY = new FoodProperties.Builder().nutrition(3).saturationModifier(0.5f).build();
    public static final FoodProperties GRAPE = new FoodProperties.Builder().nutrition(3).saturationModifier(0.5f).build();
    public static final FoodProperties CHERRY = new FoodProperties.Builder().nutrition(3).saturationModifier(0.5f).build();
    public static final FoodProperties TRUITECRUE = new FoodProperties.Builder().nutrition(2).saturationModifier(0.25f).build();
    public static final FoodProperties COOKEDTRUITECRUE = new FoodProperties.Builder().nutrition(5).saturationModifier(0.5f).build();
    public static final FoodProperties CORN = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties BACON = new FoodProperties.Builder().nutrition(2).saturationModifier(1.0f).build();
    public static final FoodProperties COOKEDBACON = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties BANANACHERRYPIE = new FoodProperties.Builder().nutrition(4).saturationModifier(1.5f).build();
    public static final FoodProperties BARCRU = new FoodProperties.Builder().nutrition(3).saturationModifier(0.1f).build();
    public static final FoodProperties COOKEDBARCRU = new FoodProperties.Builder().nutrition(5).saturationModifier(0.3f).build();
    public static final FoodProperties CACTUSOUP = new FoodProperties.Builder().nutrition(1).saturationModifier(1.0f).effect(() -> new MobEffectInstance(MobEffects.CONFUSION, 200), 1.0f).build();
    public static final FoodProperties CALAMARCRU = new FoodProperties.Builder().nutrition(1).saturationModifier(0.3f).build();
    public static final FoodProperties COOKEDCALAMARCRU = new FoodProperties.Builder().nutrition(2).saturationModifier(0.5f).build();
    public static final FoodProperties CARAMEL = new FoodProperties.Builder().nutrition(1).saturationModifier(1.5f).build();
    public static final FoodProperties CHILIMEAT = new FoodProperties.Builder().nutrition(6).saturationModifier(1.0f).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 20), 1.0f).build();
    public static final FoodProperties CHORIZO = new FoodProperties.Builder().nutrition(6).saturationModifier(1.0f).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 20), 1.0f).build();
    public static final FoodProperties CITROUILSOUP = new FoodProperties.Builder().nutrition(3).saturationModifier(1.0f).build();
    public static final FoodProperties COLINCRU = new FoodProperties.Builder().nutrition(3).saturationModifier(0.3f).build();
    public static final FoodProperties COOKEDCOLINCRU = new FoodProperties.Builder().nutrition(5).saturationModifier(0.5f).build();
    public static final FoodProperties COOKIECHOCOBLANC = new FoodProperties.Builder().nutrition(0).saturationModifier(0.0f).build();
    public static final FoodProperties CREPE = new FoodProperties.Builder().nutrition(2).saturationModifier(0.7f).build();
    public static final FoodProperties CREPECARAM = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 20), 1.0f).build();
    public static final FoodProperties CREPECHOCO = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties CREPEFROM = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties CREPESUCRE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.7f).build();
    public static final FoodProperties CUPCAKE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.1f).build();
    public static final FoodProperties CUPCAKECHOCO = new FoodProperties.Builder().nutrition(4).saturationModifier(0.1f).build();
    public static final FoodProperties CUPCAKEFRAISE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.1f).build();
    public static final FoodProperties DONUTCHOCO = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties DONUTFRAISE = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties DONUTGLACE = new FoodProperties.Builder().nutrition(4).saturationModifier(1.0f).build();
    public static final FoodProperties FROMAGE = new FoodProperties.Builder().nutrition(2).saturationModifier(0.5f).build();
    public static final FoodProperties DONUTRAISIN = new FoodProperties.Builder().nutrition(4).saturationModifier(0.1f).build();
    public static final FoodProperties FISHANDCHIPS = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties FISHSOUP = new FoodProperties.Builder().nutrition(5).saturationModifier(0.5f).build();
    public static final FoodProperties GLACEBANANE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACECAFE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACECARAMEL = new FoodProperties.Builder().nutrition(2).saturationModifier(0.8f).build();
    public static final FoodProperties GLACECERISE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACECHOCO = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACECHOCOBLANC = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACECOCO = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACEFRAISE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACEMELON = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACEPOMME = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACERAISIN = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties GLACEVANILLE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties JUSBANANE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties JUSCACTUS = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties JUSCAROTTE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties JUSCOCO = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties JUSMELON = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties JUSRAISIN = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties JUSTOMATE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties MARSHMALLOW = new FoodProperties.Builder().nutrition(2).saturationModifier(0.3f).build();
    public static final FoodProperties MARSHMALLOWSTICK = new FoodProperties.Builder().nutrition(2).saturationModifier(0.3f).build();
    public static final FoodProperties MARSHMALLOWSTICKCOOKED = new FoodProperties.Builder().nutrition(3).saturationModifier(0.3f).build();
    public static final FoodProperties MILKSHAKECARAMEL = new FoodProperties.Builder().nutrition(5).saturationModifier(0.3f).build();
    public static final FoodProperties MILKSHAKECHOCO = new FoodProperties.Builder().nutrition(5).saturationModifier(0.3f).build();
    public static final FoodProperties MILKSHAKECHOCOBLANC = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties MILKSHAKEFRAISE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties MILKSHAKEVANILLE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties OEUFDUR = new FoodProperties.Builder().nutrition(2).saturationModifier(0.3f).build();
    public static final FoodProperties PATECARBONARA = new FoodProperties.Builder().nutrition(8).saturationModifier(1.0f).build();
    public static final FoodProperties PATETOMATE = new FoodProperties.Builder().nutrition(6).saturationModifier(0.8f).build();
    public static final FoodProperties PATECHAMPI = new FoodProperties.Builder().nutrition(6).saturationModifier(0.5f).build();
    public static final FoodProperties PATEPIMENT = new FoodProperties.Builder().nutrition(6).saturationModifier(0.5f).effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 20), 1.0f).build();
    public static final FoodProperties PATEPOULET = new FoodProperties.Builder().nutrition(8).saturationModifier(0.9f).build();
    public static final FoodProperties PIZZA = new FoodProperties.Builder().nutrition(3).saturationModifier(0.8f).build();
    public static final FoodProperties POMMEDAMOUR = new FoodProperties.Builder().nutrition(6).saturationModifier(1.0f).build();
    public static final FoodProperties PATES = new FoodProperties.Builder().nutrition(4).saturationModifier(0.2f).build();
    public static final FoodProperties POPCORN = new FoodProperties.Builder().nutrition(4).saturationModifier(0.2f).build();
    public static final FoodProperties PORCARAMEL = new FoodProperties.Builder().nutrition(8).saturationModifier(1.5f).build();
    public static final FoodProperties PUREE = new FoodProperties.Builder().nutrition(5).saturationModifier(0.5f).build();
    public static final FoodProperties RAGOUTALGUES = new FoodProperties.Builder().nutrition(3).saturationModifier(0.2f).build();
    public static final FoodProperties SALADEFRUITS = new FoodProperties.Builder().nutrition(6).saturationModifier(0.3f).build();
    public static final FoodProperties SOLECRUE = new FoodProperties.Builder().nutrition(2).saturationModifier(0.2f).build();
    public static final FoodProperties SOLECUTE = new FoodProperties.Builder().nutrition(6).saturationModifier(0.8f).build();
    public static final FoodProperties SOUPELEGUMES = new FoodProperties.Builder().nutrition(7).saturationModifier(0.8f).build();
    public static final FoodProperties STEAKTARTARE = new FoodProperties.Builder().nutrition(4).saturationModifier(0.8f).build();
    public static final FoodProperties SUSHI = new FoodProperties.Builder().nutrition(4).saturationModifier(0.3f).build();
    public static final FoodProperties SOUPEPOULET = new FoodProperties.Builder().nutrition(7).saturationModifier(0.5f).build();
    public static final FoodProperties TAKOYAKI = new FoodProperties.Builder().nutrition(6).saturationModifier(0.8f).build();
    public static final FoodProperties SANDBACON = new FoodProperties.Builder().nutrition(8).saturationModifier(0.8f).build();
    public static final FoodProperties SANDBOEUF = new FoodProperties.Builder().nutrition(12).saturationModifier(1.0f).build();
    public static final FoodProperties SANDFROM = new FoodProperties.Builder().nutrition(6).saturationModifier(0.8f).build();
    public static final FoodProperties SANDJAMB = new FoodProperties.Builder().nutrition(10).saturationModifier(0.8f).build();
    public static final FoodProperties SANDPOISS = new FoodProperties.Builder().nutrition(8).saturationModifier(0.5f).build();
    public static final FoodProperties SANDPOUL = new FoodProperties.Builder().nutrition(9).saturationModifier(0.8f).build();
    public static final FoodProperties TRANCHE = new FoodProperties.Builder().nutrition(2).saturationModifier(0.5f).build();
    public static final FoodProperties CHEVALCRU = new FoodProperties.Builder().nutrition(3).saturationModifier(0.3f).build();
    public static final FoodProperties CHEVALCUIT = new FoodProperties.Builder().nutrition(8).saturationModifier(0.8f).build();


}
